#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(qtwebkit)
## This should be a short description targeted at users of your package
# Start directly with a noun or a verb, do not include “for the reMarkable”
pkgdesc="QT web browser engine"
## URL to where the project can be found on the Internet
url="https://github.com/qt/qtwebkit"
## Version of the package (see below)
pkgver=5.212.0-1
## ISO-8601 timestamp at which the source of this version was released
timestamp=2020-03-10
## Section that best matches this package
# See <https://github.com/toltec-dev/toltec/blob/stable/docs/package.md#section>
# for available sections
section=utils
## This should be your contact information
maintainer="Matt Compton <matt@xhec.dev>"
## A license under which the upstream source is available
# Choose among the list of valid SPDX license identifiers
# <https://spdx.org/licenses/>
license=lgplv2

## Which Docker image to use for building the package
# See <https://github.com/toltec-dev/toolchain> for available images
# The images are debian based and allow you to install additional packages with apt.
# Examples (version may be out of date): base:v1.1, qt:v1.1, python:v1.1, rust:v1.1
image=qt

makedepends=(
    build:bison
    build:gperf
    build:ruby
)

## Whitespace-separated list of source archives that are needed to build the package
# Archives will be automatically extracted, stripping any useless containing
# directories, and made available during the build step below
source=(
    https://github.com/qt/qtwebkit/archive/refs/tags/v5.212.0-alpha4.zip
)
## SHA-256 checksums of the source archives above
sha256sums=(
    4076bfa20e00feede3d228663719fb1b5645e00b602fc804f902cc047cd8f927
)

build() {
    mkdir build && cd build
    cmake -G Ninja -DPORT=Qt -DCMAKE_BUILD_TYPE=Release ..
    ninja
}

package() {
    cd build
    DESTDIR=$pkgdir ninja install
}